### ISSUE TITLE
Create EditScreen component

### ISSUE THREAD

**Issue by ivanalejandro0** [Unixono/beautifulthings#11]
This screen is responsible of editing/creating a specific item.

Create the small components using storybook (#7).
For the `EditScreen` component set a route using `react-router` named `#/edit`.

**Component:** `EditScreen`
This screen will show a `Header` (back, logo, save) and the _editable_ details of the item.
We will use 2 components to edit the item details: a `DatePicker` and `TextArea`.

props:
- `date`
- `text`
- `onBack`
- `onSave`

Notes: the elements used on the Header ("back", "save") will be an `ActionIcon` (#9).

**Component:** `DatePicker`
This component has a label ("When?"), a data and a picker that opens when you click/tap the date.

props:
- `date` <- the initial date to show when the component renders the first time
- `onChange` (as parameter of this function the picked date will be sent)

**Component:** `TextArea`

This component is composed of a normal html text area and a text length counter on the bottom that counts the current length of the details text area and the max length allowed (240).

props:
- `text` <- this is the initial text

exposed function:
- `getText`

**Comment by fran-costa** [comment]
DatePicker, at least on Chrome, has a "clear" button, which triggers the onChange event when clicked.

Despite it's possible to hide this button using CSS, maybe it could be a good idea to implement this component with a getDate method (as is purposed for TextArea). With this, it will be possible to validate the date inside the component and return null or a valid date and not to listen on the onChange event, what do you think?

**Comment by fran-costa** [comment]
DatePicker, at least in Chrome, has a "clear" button. Despite it's possible to remove this button with CSS (we have to do so), I think that it will be good to ensure that DatePicker always gives a valid date.

With this in mind, I think that maybe it will be better to define a default value for ```props date```, and instead of having an ```props onChange```, the DatePicker could have a ```getDate``` method. What do you think?

**Comment by fran-costa** [comment]
I've just figured out a potential problem of letting the user choose the date when adding/editting an entry:

The user can overwrite an existing entry just choosing the entry date and no warning message will be displayed (if I understood correctly, when the user tap the save button, a entry set-request must be sent to the server which must be applied it as is).

If what I'm saying is correct, we have at least two ways to solve this situation:

1. Let the user to add new enties within the current date and to edit only the text of old entries.

2. Store all entries some way locally and display a warning message if the user tries to overwrite an existing entry.

I think that the best solution is the second one because it allows the user to set the date of each entry.

I write this here because I don't know how this will be implemented and if no local storage will be used, this situation has to be considered.

**Comment by leanbalma** [comment]
I think the date picker should just be displayed when the user is editing an entry. New entries shouldn't display the date picker since the date will be always "today".
Then, in "edit mode" we should ask for confirmation before leaving the screen or selecting another date, if content has been edited.

**Comment by fran-costa** [comment]
Ok, sounds great!
