### ISSUE TITLE
Create mock of the API

### ISSUE THREAD

**Issue by chiiph** [Unixono/beautifulthings#2]
We need to mock the whole API in a module to make the development of the app completely independent of the server.

The API as was discussed is the following:

SignUp(username, password) -> error or null if ok
SignIn(username, password) -> error or token if ok
Set(token, date (string in format YYYY-MM-DD), text) -> error or null if ok
Enumerate(token, from (date YYYY-MM-DD), to (YYYY-MM-DD)) error or json with results if ok
SetPref(token, key, val) error or null if ok
GetPrefs(token) error or json if ok

The mock should have its own tests to make sure that it works as expected.

**Comment by ivanalejandro0** [comment]
Let's repurpose this issue to have an actual mock to be used when we need to test functions that use the api but without impacting the server.

The functions should be simple with close to no functionality, as reference see here: https://github.com/ivanalejandro0/beautifulthings/tree/feature/mock-api/react-app/src/api

Also, js APIs should return `undefined` instead of null if everything is ok. When you `return` or the function just ends that's the default type of return you get.

For the case of `Enumerate`, you should return a native js data type. An `Array`, an `Object`, or whatever you think it suits us better, but parsed and ready to use instead of the json we received.

**Comment by chiiph** [comment]
Do we need this mock now that we can run the server locally and/or use the one that's deployed remotely?

**Comment by fran-costa** [comment]
I'm leaving this task with low priority, I will focus on the others first.

**Comment by ivanalejandro0** [comment]
Oops, I missed this comments.
I think that eventually we will need this ticket. Most likely we are not going to work with the api directly but with wrapper functions (maybe redux actions, I'm not sure yet). And in order to test those actions we will have to mock the api. This is what this ticket is for.
We don't need it right now and we can point to this if we need it at some point.
